### ISSUE TITLE
Is OWON USB Bluetooth adapter required?

### ISSUE THREAD

**Issue by PBrunot** [DeanCording/owonb35#5]
Dear Dean,

Does this program require the (alledegly) custom USB Bluetooth 4.0 adapter ( https://eleshop.eu/owon-usb-bluetooth-dongle.html ) ? 
If not, could you provide in the readme the USB chip you used on the computer?

I'd like to port this to BT41+ but I cannot get bluetooth connection working.

Thanks in advance.

**Comment by DeanCording** [comment]
Hi Pascal,

I'm just using a standard Bluetooth dongle which has Bluetooth Low Energy (BLE) 
support (ie Bluetooth 4.0).

Looking at the Owon dongle's web page, I don't believe what they are saying about 
it not being possible to use a universal dongle because the meters can be used with 
Android phones which don't have this special Owon Bluetooth module, just a 
standard Bluetooth one.

The adapter I use is a Simplecom NB405 Bluetooth USB dongle https://
www.simplecom.com.au/simplecom-nb405-usb-bluetooth-4-0-csr-adapter-wireless-
dongle-with-a2dp-edr.html[1] .  It has a standard Cambridge Silicon Radio Bluetooth 
4.0 chipset.  USB Id 0a12:0001


Cheers,

Dean




On Friday, 9 April 2021 08:30:14 AEST Pascal Brunot wrote:
> Dear Dean,
> 
> Does this program require the (alledegly) custom USB Bluetooth 4.0 adapter (
> https://eleshop.eu/owon-usb-bluetooth-dongle.html ) ? If not, could you
> provide in the readme the USB chip you used on the computer?
> 
> I'd like to port this to BT41+ but I cannot get bluetooth connection
> working.
> 
> Thanks in advance.



--------
[1] https://www.simplecom.com.au/simplecom-nb405-usb-bluetooth-4-0-csr-adapter-wireless-dongle-with-a2dp-edr.html

**Comment by PBrunot** [comment]
Thanks. I ended up creating a Javascript based interface : https://github.com/PBrunot/owonb41t
Couldn't have managed it without your documentation. 
Thanks!
